### ISSUE TITLE
Dialog is hidden beyond application. 

### ISSUE THREAD

**Issue by czbird77** [insanj/Bluepicker#2]
When invoking bluepicker from home screen, everything is OK. 
But when invoking bluepicker when another another application is open (e.g. safari), the bluetooth gets started (icon shows in the status bar) but the device selection dialog is shown behind the application window, so that it is inaccessible. Please make the dialog go to front. 

Device: iPad mini 2, iOS 7.0.4
Activator action: slide right on status bar

**Comment by asadia** [comment]
Is there a simple way to implement the rudimentary fix mentioned above? Bluepicker is my main tweak for my iPad Mini 1 on 8.1.2 and it would be nice to be able to use it from inside any app as well as the lockscreen and homescreen. Thanks!
